spring:
  application:
    name: Bank_REST
  datasource:
    url: jdbc:mysql://localhost:3306/bankrest?useSSL=false
    username: root
    password: xufjor-todsiB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml
server:
  port: 8080
