spring:
  application:
    name: Bank_REST
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:bankrest}?useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database: MYSQL
  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer
server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
